language: node_js

node_js:
- lts/*
- node

before_deploy:
  - npm run build
  - npm version $TRAVIS_TAG

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    node: node # Only publish with latest node version
    repo: jsonapi-suite/jsorm
